name: CI - Build Test Scan

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflow/ci.yml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t rajgltichmax/K8s-project:${{ github.sha }} \
            -t rajflitchmax/K8s-project:latest \
            backend/

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: rajgltichmax/K8s-project:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Push image 
        run: |
          docker push rajgltichmax/K8s-project:${{ github.sha }}
          docker push rajgltichmax/K8s-project:latest